package com.example.notehut.Model

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.android.parcel.Parcelize

@Entity(tableName = "Notes")
@Parcelize
class Notes(
    @PrimaryKey(autoGenerate = true)
    var id:Int ?= null, // unique id auto generated by SQLite
    var title:String,
    var subTitle:String,
    var notes:String,
    var date:String,
    var priority:String
    ) : Parcelable